<?php

namespace Webberdoo\AppBundle\Repository;

/**
 * ApiKeyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApiKeyRepository extends \Doctrine\ORM\EntityRepository
{
    public function getFirstSetting()
    {
        return $this->createQueryBuilder('api')
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
