<?php

namespace Webberdoo\AppBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCategoryAndVideos($slug)
    {
        return $this->createQueryBuilder('category')
            ->andwhere('category.slug = :slug')
            ->andWhere('vid.status = :status' )
            ->setParameter('status', 1)
            ->setParameter('slug', $slug)
            ->leftJoin('category.videos', 'vid')
            ->addSelect('vid')
            ->getQuery()
            ->execute();
    }

    public function getCategoryAndVideosHome()
    {
        return $this->createQueryBuilder('category')
         //   ->andwhere('category.slug = :slug')
            ->andwhere('category.showOnHome = :home')
            ->andWhere('vid.status = :status' )
            ->setParameter('status', 1)
            ->setParameter('home', 1)
           // ->setParameter('slug', $slug)
            ->leftJoin('category.videos', 'vid')
            ->addSelect('vid')
            ->getQuery()
            ->execute();
    }

    public function getCategoryAndVideosPaginated($slug, $offset ,$maxResults)
    {
        return $this->createQueryBuilder('category')
            ->andWhere('category.slug = :slug')
            ->andWhere('videos.status = :status' )
            ->setParameter('status', 1)
            ->setParameter('slug', $slug)
            ->leftJoin('category.videos', 'videos')
            ->setFirstResult($offset)
            ->setMaxResults($maxResults)
            ->addSelect('videos')
            ->getQuery()
            ->execute();
    }
}
