<?php

namespace Webberdoo\AppBundle\Repository;

/**
 * ChannelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChannelRepository extends \Doctrine\ORM\EntityRepository
{
    public function getChannelsPaginated($offset ,$maxResults)
    {
        return $this->createQueryBuilder('channel')
            ->setFirstResult($offset)
            ->setMaxResults($maxResults)
            ->getQuery()
            ->execute();
    }

    public function getChannelAndVideos($slug)
    {
        return $this->createQueryBuilder('channel')
            ->andwhere('channel.slug = :slug')
            ->andWhere('vid.status = :status' )
            ->setParameter('status', 1)
            ->setParameter('slug', $slug)
            ->leftJoin('channel.videos', 'vid')
            ->addSelect('vid')
            ->getQuery()
            ->execute();
    }

    public function getChannelAndVideosPaginated($slug,$offset ,$maxResults)
    {
        return $this->createQueryBuilder('channel')
            ->andwhere('channel.slug = :slug')
            ->andWhere('vid.status = :status' )
            ->setParameter('status', 1)
            ->setParameter('slug', $slug)
            ->leftJoin('channel.videos', 'vid')
            ->setFirstResult($offset)
            ->setMaxResults($maxResults)
            ->addSelect('vid')
            ->getQuery()
            ->execute();
    }
}
