<?php

namespace Webberdoo\AppBundle\Repository;

/**
 * PasswordHashRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PasswordHashRepository extends \Doctrine\ORM\EntityRepository
{
}
