<?php

namespace Webberdoo\AppBundle\Repository;

/**
 * SettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SettingRepository extends \Doctrine\ORM\EntityRepository
{
    public function getFirstSetting()
    {
        return $this->createQueryBuilder('setting')
          //  ->where('setting.id = :id')
       //     ->setParameter('id', $id)
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
