<?php

namespace Webberdoo\AppBundle\Repository;

/**
 * WidgetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WidgetRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllWidgets($position)
    {
        return $this->createQueryBuilder('widget')
            ->andwhere('widget.status = :status')
            ->andwhere('widget.position = :position')
            ->setParameter('status', 1)
            ->setParameter('position', $position)
            ->getQuery()
            ->execute();//get as array of results
    }
}
